name: Pixeebot

on:
  pull_request:

permissions:
  contents: read
  id-token: write


jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: ask for fixes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SECRET=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://app.pixee.ai" | jq -j '.value')
          API_RESPONSE=$(curl -v -X POST -H "Authorization: Bearer $SECRET" "https://r0u25801yg.execute-api.us-east-1.amazonaws.com/prod/analysis-input/ryandens/semgrep-test/${{ github.event.pull_request.number }}")
          echo "$API_RESPONSE"
          echo $SECRET